### ISSUE TITLE
@ nccgroup, Please how can i Replace all my values at once? and get the response 

### ISSUE THREAD

**Issue by workfast108** [nccgroup/AutoRepeater#10]
Firstly Thank you for the amazing tool,  i have a question Please, Assuming i have to replace one Request Header Value,  e.g CSRF Header,  and Maybe two Cookies Value  Request. , when i make the setting is autorepeater, it is actually replacing one at a time, which will not let me get desire result.

Am thinking of a situation where by when the Replacement setting are Set Autorepeater use those setting at once. what i have notice till now is that, Autorepeater usually Replaces  CSRF Header Value , only in the First Request and in the Next "Modified Request" it return the Old  CRSF Header that was with the original request again, and Replaces one of the  Cookies Value, then next it will Replace, the last Cookie Value Set, and keep Original  CSRF Header Value, so there will be no way all the Settings are Completely Replace at once ,or together at the same time ,  in the Modified Request. this make it difficult to get the actually desire result or to know if the test was successful. i don't know if am doing anything wrong. am waiting for your response.

Warm Regards
Dere sewa

**Comment by m00r3** [comment]
hey @workfast108, to replace multiple values within one request, set all of the values you want replaced within the "Base Replacement" table. Each replacement in the "Base Replacement" table will be applied to the request at the same time. Afterwords, AutoRepeater will make a new request for each replacement set within the "Replacements" with every replacement in the "Base Replacement" table already applied. This should allow you to replace multiple headers and cookies at the same time. 

Thanks,
Justin

**Comment by workfast108** [comment]
OMG ,Honestly your quick response, just  humble me, you are great Bro. please let me juz give you example of what i wanna do here: Please what is the Best Match Up to use in this scenario
I need to Replace to Cooke Value and One Header Value  all at once, i mean at one time how do i set the Base Replacement and the second Replacement
In the Header Side: i want to Replace 
Header Name       Header Value
X-CSRF-Token: 91053b50cfc2e0ee0
============================================================

inside  the Cookie
cookie name                   Cookie value
Workfast_website=   2a23c7487acb7467c406235adf57

cookie Name                Cookie value
csrf_token_website=  91053b50cfc2e0ee
==============================================================
i want to Replace  all  the above  cases with 
Header name             Header Value
X-CSRF-Token:  c5c047284d2b51f

======================================================

Cookie Name                          Cookie Value
workfast_website= cafef35317e0b1b89b65199

Cookie name                  Cookie Value 
csrf_token_website= c5c047284d2b51fa041822b9e2

Thank You

**Comment by m00r3** [comment]
hey @workfast108,

If I'm understanding correctly, you'd want something along the lines of: 

### Base Replacements
Type: Request Header
Match: X-CSRF-Token: 91053b50cfc2e0ee0
Replace: X-CSRF-Token: c5c047284d2b51f

Type: Match Cookie Name, Replace Value
Match: Workfast_website
Replace: cafef35317e0b1b89b65199

Type: Match Cookie Name, Replace Value
Match: csrf_token_website
Replace: c5c047284d2b51fa041822b9e2

### Replacements

You don't need to specify any replacements here if you only want to change those three values, however, add any additional replacements they have the modifications from above applied.

Thanks,
Justin

**Comment by workfast108** [comment]
@justinmoore-ncc  Thank You for Everything, it worked Perfectly well, Please i have this last Question to ask you , it as to do with ID's , assuming ID's is in the URL Parameters, and i have some ID's as a Post request body Parameter's  as well.

suppose  (1)  URL is like  PUT /users/459461979/ and i want to replace it with " PUT  /users/411839370/ 

and (2) the Post request body , i have things like ,"user_id":459461979,  and what to replace it with  " "user_id: 411839370
what "Type" combination  Best Suit the URL  scenario and what "Type" Combination  Best Suit the Post body request Parameter?

Thank You
Dere Sewa

**Comment by m00r3** [comment]
Hey @workfast108,

The following replacement will replace all instances of "459461979" with "411839370". 

### Base Replacements 
Type: Request String
Match: 459461979
Replace: 411839370
Which: Replace All

Thanks,
Justin

**Comment by workfast108** [comment]
@justinmoore-ncc  Thanks for your great response i appreciate 

Warm regards
Dere Sewa

**Comment by m00r3** [comment]
@workfast108 no problem, I'm happy to help.

**Comment by 99smith** [comment]
Hi @justinmoore 

I have a situation where I need to use - match parameter name and replace its value .

For example I have GET request like this: GET https://exmple.com?dateStart=xyzee

Now when I use - match parameter name and replace its value and set parameter name as dateStart and value as superman

Autorepeater just works perfectly fine : https://exmple.com?dateStart=superman

Now the problem is 

I have a post request in which there is json body like this 

{"userId":"US-DG46","dateStart":"2022-03-20","dateEnd":"2022-04-20"}

Now for the same above condition autorepeater doenot replace value of dateStart in json body parameter.

How can I achive this . Please help !

Thanks you
