### ISSUE TITLE
Extra request with active base replacement and disabled replacement

### ISSUE THREAD

**Issue by JJJJust** [nccgroup/AutoRepeater#11]
When I have an activated base replacement and only a disabled replacement exists, I end up sending two identical requests that reflect the effects of the base replacement.

The disabled replacement doesn't seem to be doing anything, but a request still seems to be fired because it's there.

**Comment by m00r3** [comment]
Hey @JJJJust,

Thanks for opening the issue. I look into this sometime this week and get a fix out.

**Comment by m00r3** [comment]
Hey @JJJJust , 
This should be fixed in the latest JAR now. Feel free to reopen the issue if it's not.
