### ISSUE TITLE
Save and Load from config file

### ISSUE THREAD

**Issue by danielthatcher** [nccgroup/AutoRepeater#16]
It would be helpful to be able to save and load a set of replacements from a config file that's independent of burp's state.

This would probably be useful for quite a few situations, but as an example, I'm currently using AutoRepeater to aid with SQLi testing, and each test I have to set up quite a few replacements manually. It would be much quicker to be able to load these in from a config file.

**Comment by justinmoore** [comment]
hey @danielthatcher,

I completely agree. This bit of functionality I wanted to add in the near future with the goal of also providing some loadable configs for folks to pull from the git repo as examples.

**Comment by justinmoore** [comment]
I'm working on this now.

**Comment by justinmoore** [comment]
AutoRepeater does this now. Let me know if there's any issues with it.

**Comment by danielthatcher** [comment]
Finally got a chance to play around with this at work (hence commenting on this a  month later - sorry about that), and it's to be working well. Thanks for implementing it.

A colleague and I started playing around with building up some configs, and one thing that we noted is that it might be easier if the configs were stored as JSON rather than Base64 encoded JSON as this would work better with version control. You mentioned that you might also like to have some configs for people to pull in from the git repo, so I believe it would help there too.

**Comment by justinmoore** [comment]
hey @danielthatcher,

I agree that it doesn't make a whole lot of sense to store the configs in based64ed JSON. The only reason it's like that is because I wasn't sure how I was going to store the files at the time I was writing it and never got around to fixing it. I'll change it now to support both to make handwriting configs a bit easier. 

Thanks,
Justin

**Comment by justinmoore** [comment]
hey @danielthatcher,

Just to close the loop on this, I've changed the config file format to be JSON instead of Base64 encoded JSON. AutoRepeater will gracefully handle the transition if you have any existing import files.

Thanks,
Justin
