### ISSUE TITLE
Add an "Anywhere" type

### ISSUE THREAD

**Issue by danielthatcher** [nccgroup/AutoRepeater#18]
Replacements are currently limited to specific locations ("Request String", "Request Header", etc.). Another replacement type could be added to allow for searching the whole request for replacements, rather than just specific locations.

**Comment by justinmoore** [comment]
Hey @danielthatcher ,

I think the "request string" replacement provides this functionality. It just looks for the first instance / every instance of a specific regex or string within the entire contents of the request and replaces it.

**Comment by danielthatcher** [comment]
Ah, sorry about that. I had taken "Request String" to mean the query string of the request. It might be worth renaming this, but that might just be me.

**Comment by justinmoore** [comment]
Yeah, I couldn't think of a better name for it and I agree it's ambiguously named. If can think of something better to call it i'd be down for the change.
