### ISSUE TITLE
Add Proxy > HTTP History functionality to AutoRepeater Log

### ISSUE THREAD

**Issue by leesoh** [nccgroup/AutoRepeater#21]
First off, thanks for making and supporting this tool. It's pretty slick!

I'm currently testing a large multi-role application and it would be really helpful to be able to gain access to the same sort of right-click functionality available in HTTP history (send to, highlight, comment, etc.) in the AutoRepeater log.

**Comment by leesoh** [comment]
Adding to this, the filter options would be 👌

**Comment by justinmoore** [comment]
hey @leesoh ,

Thanks for finding my tool useful. I agree that adding some better log management would be definitely useful. In the interim, you might find that logger++ provides some of the functionality you want within a separate plugin.

**Comment by justinmoore** [comment]
I'm going to close this issue now. 

I've added highlighting to the log. I don't think commenting really makes a ton of sense given the automated nature of this tool, and you can send the request to the other tools from the request viewer. If there's anything other features you're interested in having included feel free to open a new issue.

Thanks,
Justin
