### ISSUE TITLE
Import Suggestions

### ISSUE THREAD

**Issue by jacobheath** [nccgroup/AutoRepeater#22]
Fellow NCCer here. I'm wondering if you have recommendations or plans for an import feature? My current engagement has 8 roles and I'd like to test them all at the same time with different tabs. However, when Burp inevitably dies, all the set up of those 8 tabs is lost. Any chance I can upload a JSON file that would configure my tabs? Thanks

**Comment by justinmoore** [comment]
Also if you need to tweak any of the exported files by hand the format is base64 encoded JSON (session expire, tokens change, etc).

**Comment by jacobheath** [comment]
Nice! I should have read the commit messages 👍 . Also, the BAppsStore appears to have a much older version available.

**Comment by justinmoore** [comment]
Yeah, the BApp store version is a bit older. It's a little bit of a process to get it updated so I've been putting it off.

**Comment by jacobheath** [comment]
So when import and try to receive requests from Proxy, I get the following exception:

~~~java
a.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@ea76c1e rejected from java.util.concurrent.ThreadPoolExecutor@23d4c3d4[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at burp.AutoRepeater.modifyAndSendRequestAndLog(AutoRepeater.java:1242)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:201)
	at burp.pkf.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
~~~

**Comment by jacobheath** [comment]
I think I used this one. The error doesn't always happen though. I have tried to trigger it, but am having trouble. Seems to happen a various times.
[autorepeater.zip](https://github.com/nccgroup/AutoRepeater/files/2116541/autorepeater.zip)

**Comment by justinmoore** [comment]
So it seems that this is an issue with the JVM running out of threads and not with the import function itself. This should be pretty straight forward to fix and I should have a patch out shortly.

**Comment by justinmoore** [comment]
This should be fixed in the newest JAR now. I'll wait for confirmation before I close this.

**Comment by justinmoore** [comment]
I'll close this now assuming it's fixed. If this issue persists feel free to reopen this issue and i'll give it another look.
