### ISSUE TITLE
Auto-Hide/Expand AutoRepeater's Settings Pane

### ISSUE THREAD

**Issue by ngkogkos** [nccgroup/AutoRepeater#26]
As per issue, if there is an easy way, it would be nice to auto-hide the settings pane as it takes up too much space on screen and if more info is added in the result columns, it will be even more.

It could auto-hide, and expand again only when tester moves their cursor over the right side area.

**Comment by justinmoore** [comment]
Hey @ngkogkos,

I'm unsure how to automatically show/hide the settings pane, however, I'm going to add the pane's visibility as a toggleable option in the right click menu. Precious screen real estate is definitely something I'm interested in maximizing and this is a feature I'm going to implement ASAP.

Thanks,
Justin

**Comment by justinmoore** [comment]
Hey @ngkogkos,

Adding this as a right-click option didn't quite work out, however, I added a MenuItem to Burp Suite's JMenuBar that now has the option to show/hide the options panel. 

The new JAR in the git repo has this feature. I'm going to close this issue now, if there's any issue feel free to reopen the issue. 

Thanks,
Justin
