### ISSUE TITLE
Migrate Import/Export options to Burp Menu

### ISSUE THREAD

**Issue by justinmoore** [nccgroup/AutoRepeater#28]
Now that there's an AutoRepeater menu item I should move the import/export options to it to free up space within the AutoRepeater plugin UI.

**Comment by Sinderella** [comment]
If you don't mind, I am working on this issue. PR will be coming later today once I got home. 😆

**Comment by justinmoore** [comment]
Fantastic!

I appreciate the contribution.

**Comment by justinmoore** [comment]
Thanks to the contributions of @Sinderella this is implemented now.
