### ISSUE TITLE
Log filter whitelist/blacklist radio button

### ISSUE THREAD

**Issue by Sinderella** [nccgroup/AutoRepeater#34]
They have to be pressed twice in order for the logs to correspond with the filters. Is this expected?

**Comment by justinmoore** [comment]
yeah, there's a bug in there that I have fixed in the branch I'm currently working on. It should be fixed sometime today when I push out the log highlighting feature.

**Comment by justinmoore** [comment]
This is fixed now. Please let me know if there's any issues with the fix. 

Thanks,
Justin
