### ISSUE TITLE
Option to turn off log filter

### ISSUE THREAD

**Issue by Sinderella** [nccgroup/AutoRepeater#35]
May be it's just not too obvious for me to get the log filter working the way I wanted it to be. An option to turn off the filter is nice to have when we are trying to see if we have configured something wrong and want it to show everything.

**Comment by justinmoore** [comment]
By default the log filter shouldn't be filtering any logs. Can you share the filter configuration you're using that's having issues?

**Comment by Sinderella** [comment]
Please see the images below:

![image](https://user-images.githubusercontent.com/1926450/42931777-7c5a0c6a-8b38-11e8-8cb2-e91817d85b22.png)

![image](https://user-images.githubusercontent.com/1926450/42931786-82757292-8b38-11e8-8804-5aa4eb56e593.png)

![image](https://user-images.githubusercontent.com/1926450/42931792-892c0ec0-8b38-11e8-8067-1522ae6334a5.png)

I am trying to remove the cookie header from the requests, I am not sure if there is a better approach. Anyway, I have sent some requests to AutoRepeater and the logs are still empty.

**Comment by justinmoore** [comment]
There was a bug where I was initializing the filter as a blacklist when it was a whitelist by default which was causing the issue. I've merged the fix and it should be resolved now in the latest JAR.

Additionally, I've added a "Remove Header By Name" replacement so it should be as easy as setting the Replacement to "Remove Header By Name" and the value to "Cookie". 

Please let me know if there's any issues with these fixes/features.

Thanks,
Justin
