### ISSUE TITLE
Failing content length validation 

### ISSUE THREAD

**Issue by cetriext** [nccgroup/AutoRepeater#51]
I'm using regex to match and  replace values in POST request
the server is validating Content-Length: value   
AutoRepeater is not adding this  header.
I'm able to add Content-Length:    header but i'm not sure how  content-length value can be automatically updated in each request as the value is different for each request because of regex based mach and replace rule?

**Comment by justinmoore** [comment]
Hey @Cetriext,

Can you please provide an example of an request and replacements that are causing this issue? 

Thanks,
Justin

**Comment by droope** [comment]
I also have this issue now, content-type does not get updated on "request string" parameter replacements.
