### ISSUE TITLE
Not working in latest version of burp

### ISSUE THREAD

**Issue by vulnh0lich2** [nccgroup/AutoRepeater#55]

**Comment by dokkillo** [comment]
yes, its true, dont work.
I try to add requests to autorepeater and nothing happen

**Comment by justinmoore** [comment]
Hey folks,

I downloaded the newest version of burp and AutoRepeater does appear to be working as intended. You can try by setting a string replacement for google and replacing it with test and then loading google.com.

Thanks,
Justin

**Comment by dokkillo** [comment]
Justinmoore you are true, its working! ty!

**Comment by justinmoore** [comment]
That’s great to hear. I’m going to close this issue out. If it pops back up for persists feel free to reopen it.

Thanks,
Justin

**Comment by vdb-sander** [comment]
Autorepeater doesn't work in Burp Professional v2.1.04
