### ISSUE TITLE
Repeated entries

### ISSUE THREAD

**Issue by bsysop** [nccgroup/AutoRepeater#60]
Hi, first i wanna say congrats for that extension, very helpful!

I configured one tab to listen on proxy, and when navigate to same url he repeat everything again, do you have some way to prevent that? (just one request per URL)

Thx

**Comment by justinmoore** [comment]
Hey @bsysop,
AutoRepeater does not have the ability to track which URLs requests have already been sent to. If you're looking to have a single request get set through the rules you can use the "Send To AutoRepeater" functionality to have the request get sent only once.
Thanks,
Justin
