### ISSUE TITLE
Top menu gone missing in newer versions of BurpSuite

### ISSUE THREAD

**Issue by 1lastBr3ath** [nccgroup/AutoRepeater#82]
Hello,

The top menu of AutRepeater doesn't load in newer versions of BurpSuite. Can we please fix it? I was told that it needs to be done after initialization which in this case is happening *before* initialization. 

Regards,

**Comment by DolphFlynn** [comment]
Hi @1lastBr3ath. This is fixed by https://github.com/PortSwigger/auto-repeater/pull/3 but the version in the BApp store hasn't been updated yet. In the interim, if you clone PortSwigger's repo then you can get the fix. If you need help building then let me know.

**Comment by 1lastBr3ath** [comment]
Thanks, I didn't know the version in BApp was updated but it still lacks the "Duplicate" button, so maybe still behind some commits. I hope they update the version in BApp store soon anyway. Thank you again!!

**Comment by bryceatmandiant** [comment]
I tried using the jar file from Portswigger's repo (from the link you have above) and wasn't successful. Do I need to rebuild the extension completely?

**Comment by 1lastBr3ath** [comment]
@bryceatmandiant That jar file is 4 years old. I've forked the repo and have added the jar in [releases](https://github.com/1lastBr3ath/AutoRepeater/releases). I hope that helps.
